# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

FROM nvidia/cuda:11.0-cudnn8-devel-ubuntu18.04

USER root:root

##############################################################################
# Environment variables
##############################################################################

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV DEBIAN_FRONTEND noninteractive
ENV LD_LIBRARY_PATH "/usr/local/cuda/extras/CUPTI/lib64:${LD_LIBRARY_PATH}"

ENV STAGE_DIR=/root/gpu/install \
    CUDA_HOME=/usr/local/cuda \
    CUDNN_HOME=/usr/lib/x86_64-linux-gnu \
    CUDACXX=/usr/local/cuda/bin/nvcc

RUN mkdir -p $STAGE_DIR

RUN apt-get -y update && \
    apt-get --assume-yes --no-install-recommends install \
    build-essential \
    autotools-dev \
    curl \
    wget \
    openssh-server \
    openssh-client \
    tmux \
    vim \
    sudo \
    g++ \
    gcc \
    git \
    bc \
    tar \
    bash \
    pbzip2 \
    pv bzip2 \
    cabextract \
    dos2unix \
    less \
    unzip \
    pdsh \
    pssh \
    nfs-common \
    libfuse-dev \
    htop iftop iotop rsync iputils-ping \
    net-tools && \
    rm -rf /var/lib/apt/lists/*

##############################################################################
# Conda Environment
##############################################################################
# MiniConda with python 3.7.7
ARG MINICONDA_VERSION=4.7.12.1  
ARG PYTHON_INSTALL_VERSION=3.7.7

ENV MINICONDA_VERSION ${MINICONDA_VERSION}
ENV PATH /opt/miniconda/bin:$PATH
RUN wget -qO /tmp/miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-${MINICONDA_VERSION}-Linux-x86_64.sh    && \
    bash /tmp/miniconda.sh -bf -p /opt/miniconda && \
    conda clean -ay && \
    rm -rf /opt/miniconda/pkgs && \
    rm /tmp/miniconda.sh && \
    find / -type d -name __pycache__ | xargs rm -rf

##############################################################################
# Generic ENV
##############################################################################
ENV LD_LIBRARY_PATH "$LD_LIBRARY_PATH:/usr/local/lib:/usr/lib/x86_64-linux-gnu"
ENV STAGE_DIR "/root/gpu/install"
RUN mkdir -p $STAGE_DIR

#############################################################################
# IB user space libs  Mellanox driver should be installed on kernel space already
#############################################################################

RUN apt-get update && apt-get install -y --no-install-recommends  libnuma-dev  libmlx4-1      libmlx5-1      librdmacm1     libmthca1      libdapl2      dapl2-utils      openssh-client      openssh-server      iproute2 && rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y --no-install-recommends cpio libmlx4-1 libmlx5-1 librdmacm1 libmthca1 libdapl2 dapl2-utils pciutils ibutils ibverbs-utils rdmacm-utils infiniband-diags perftest librdmacm-dev && rm -rf /var/lib/apt/lists/*

##############################################################################
# nv_peer_mem
##############################################################################
RUN apt-get -y update && apt-get install -y --no-install-recommends debhelper dkms && rm -rf /var/lib/apt/lists/*
RUN mkdir -p ${STAGE_DIR} && \
    git clone https://github.com/Mellanox/nv_peer_memory.git ${STAGE_DIR}/nv_peer_memory && \    
    cd ${STAGE_DIR}/nv_peer_memory && \
    git checkout 4ed7715d62edf1cbcbb522a9f9a0efb13e43b0d0 && \  
    ./build_module.sh && \
    cd /tmp && \
    tar xzf /tmp/nvidia-peer-memory_1.1.orig.tar.gz && \
    cd nvidia-peer-memory-1.1 && \
    dpkg-buildpackage -us -uc && \
    dpkg -i ../nvidia-peer-memory_1.1-0_all.deb
WORKDIR $STAGE_DIR

##############################################################################
# OPENMPI
##############################################################################
ENV OPENMPI_BASEVERSION=4.0
ENV OPENMPI_VERSION_STRING=${OPENMPI_BASEVERSION}.5
RUN cd ${STAGE_DIR} && \
    wget -q -O - https://download.open-mpi.org/release/open-mpi/v${OPENMPI_BASEVERSION}/openmpi-${OPENMPI_VERSION_STRING}.tar.gz | tar xzf - && \
    cd openmpi-${OPENMPI_VERSION_STRING} && \
    ./configure  --enable-orterun-prefix-by-default && \
    make uninstall && \
    make -j"$(nproc)" install && \
    # Sanity check:
    test -f /usr/local/bin/mpic++ && \
    ldconfig && \
    cd ${STAGE_DIR} && \
    rm -r ${STAGE_DIR}/openmpi-${OPENMPI_VERSION_STRING}
ENV PATH=/usr/local/bin:${PATH} \
    LD_LIBRARY_PATH=/usr/local/lib:${LD_LIBRARY_PATH}


ENV CMAKE_VERSION=3.16.4
RUN cd /usr/local && \
    wget -q -O - https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz | tar zxf -
ENV PATH=/usr/local/cmake-${CMAKE_VERSION}-Linux-x86_64/bin:${PATH}

WORKDIR /workspace

##############################################################################
# Some Packages
##############################################################################
RUN apt-get -y update && apt-get -y install --no-install-recommends \
    software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa -y && \
    echo "deb http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64 /" > /etc/apt/sources.list.d/nvidia-ml.list && \
    apt-get update && apt-get install -y --allow-change-held-packages --allow-downgrades --no-install-recommends \
    ca-certificates \
    libjpeg-dev \
    libpng-dev \
    libsndfile-dev \
    libcupti-dev \
    libjpeg-dev \
    libpng-dev \
    screen \
    libxml2-dev \
    libxslt-dev &&\  
    rm -rf /var/lib/apt/lists/*


##############################################################################
# Setup conda environment, cuda
##############################################################################
RUN conda install -y python=$PYTHON_INSTALL_VERSION pyyaml scipy ipython cython typing mkl mkl-include setuptools
RUN echo /usr/lib/x86_64-linux-gnu >> /etc/ld.so.conf.d/cuda-11-0.conf
RUN ldconfig
    
##############################################################################
# PyTorch, tensorboard, transformers, and supports
##############################################################################
## Pinning PIP b/c https://azure.github.io/azureml-sdk-for-r/articles/troubleshooting.html#training
RUN python -m pip install --upgrade pip==20.1.1
COPY requirements.txt /workspace
RUN pip install --no-cache-dir -r requirements.txt

############################################
# Install Apex
# https://github.com/NVIDIA/apex/issues/988
############################################
RUN pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" \
    git+git://github.com/NVIDIA/apex.git@0c2c6eea6556b208d1a8711197efc94899e754e1

############################################
# Install DeepSpeed from source
############################################
RUN pip install -v git+git://github.com/microsoft/DeepSpeed.git@6ba96289702afc56948aa9f6cff55d7df678ccc0
RUN ds_report